# Generated by Django 4.1.7 on 2023-02-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookfast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appo_date', models.CharField(max_length=10)),
                ('appo_time', models.IntegerField()),
                ('patient_name', models.CharField(max_length=200)),
                ('doc_name', models.CharField(max_length=200)),
            ],
        ),
    ]
