# Generated by Django 4.1.7 on 2023-03-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookfast', '0003_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='registartion',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registartion',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registartion',
            name='phone_no',
            field=models.CharField(max_length=100),
        ),
    ]
