# Generated by Django 4.1.7 on 2023-04-03 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookfast', '0004_registartion_gender_registartion_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_speciality', models.CharField(max_length=255)),
                ('doctor_no', models.IntegerField()),
                ('doctor_img', models.ImageField(upload_to='uploads/doctor/')),
                ('doctor_email', models.CharField(max_length=255)),
                ('doctor_present', models.CharField(max_length=255)),
                ('doctor_previous', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='doctors',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookfast.hospital'),
        ),
    ]
