# Generated by Django 4.1.7 on 2023-04-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookfast', '0007_alter_doctor_doctor_no_alter_hospital_hospital_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appo_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
