# Generated by Django 4.1.7 on 2023-05-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookfast', '0009_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=50, null=True)),
                ('hos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookfast.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookfast.registartion')),
            ],
        ),
    ]
