# Generated by Django 4.1.7 on 2023-05-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookfast', '0010_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='review',
        ),
    ]
