# Generated by Django 4.1.7 on 2023-02-23 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_speciality', models.CharField(max_length=255)),
                ('doctor_no', models.IntegerField()),
                ('doctor_img', models.ImageField(upload_to='uploads/doctor/')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='registartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('phone_no', models.IntegerField()),
                ('date_of_birth', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_address', models.CharField(max_length=100)),
                ('hospital_no', models.IntegerField()),
                ('hospital_dec', models.CharField(max_length=255)),
                ('hospital_img', models.ImageField(upload_to='uploads/hospital/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookfast.doctors')),
            ],
        ),
    ]
