# Generated by Django 4.1.7 on 2023-03-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookfast', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_text', models.CharField(max_length=300)),
            ],
        ),
    ]
